### ISSUE TITLE
Mini keyboard with a built-in touchpad (Bluetooth)

### ISSUE THREAD

**Issue by rtek1000** [Peluko/BLERetro32#1]
Hello,

Do you know if it is possible to adapt this lib to work with a mini keyboard with a built-in touchpad?

Like this one (Amazon.com):
- Mini Bluetooth Keyboard with Touchpad  https://a.co/d/b1zIXxR

The USB version has 2 HID interfaces, so not just any driver will work. Generally, microcontrollers support only 1 HID interface.

**Comment by rtek1000** [comment]
The idea is to be able to use the keyboard on new displays that already have the ESP32 integrated on the board.

Ref.: https://a.aliexpress.com/_mNtu8ii

**Comment by Peluko** [comment]
Hello. I think that this is not the use case for this lib. You should use directly some Bluetooth LE library, like the one I'm using on this project, https://github.com/h2zero/NimBLE-Arduino

**Comment by rtek1000** [comment]
I thought it would be easier for anyone who has already managed to make a Host HID controller for Joystick, to adapt the code for Keyboard and Mouse. But I thank you for your attention.

![ESP32_Bluetooth_Host_HID](https://github.com/Peluko/BLERetro32/assets/8660811/85d01638-1406-45d7-8270-85200fe93a64)
